
title: Le vent se lÃ¨ve
author: Eric Wang
description: just playing around
remote_theme: jekyll/minima
minima:
  skin: dark
header_pages:
  - main.md
  - math.md
  - about.md
  - links.md
